"""
TTS Guard — PDF Inspection Report Generator
Generates professional PDF reports with TTS branding and Civil Defence reference.
"""

import os
from datetime import date
from fpdf import FPDF

ASSETS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "assets")
LOGO_PATH = os.path.join(ASSETS_DIR, "logo.png")


class InspectionReport(FPDF):
    """Custom PDF class for TTS inspection reports."""

    def __init__(self, building_name, client_name, **kwargs):
        super().__init__(**kwargs)
        self.building_name = building_name
        self.client_name = client_name

    def header(self):
        # Fire red header bar
        self.set_fill_color(211, 47, 47)  # #D32F2F
        self.rect(0, 0, 210, 12, "F")

        # Logo or text fallback
        if os.path.exists(LOGO_PATH):
            try:
                self.image(LOGO_PATH, 10, 15, 30)
                x_start = 45
            except Exception:
                x_start = 10
        else:
            x_start = 10

        # Company info
        self.set_y(16)
        self.set_x(x_start)
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(211, 47, 47)
        self.cell(0, 8, "Talent Technical Services", ln=True)
        self.set_x(x_start)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, "Fire Safety AMC Management  |  Abu Dhabi, UAE  |  +971 2 66 78340", ln=True)

        # Report title
        self.ln(4)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(33, 33, 33)
        self.cell(0, 8, "FIRE SAFETY INSPECTION REPORT", ln=True, align="C")

        # Orange accent line
        self.set_draw_color(255, 111, 0)  # #FF6F00
        self.set_line_width(0.8)
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(6)

    def footer(self):
        self.set_y(-30)
        # Civil Defence reference section
        self.set_draw_color(200, 200, 200)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(2)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(130, 130, 130)
        self.cell(0, 4,
                  "Abu Dhabi Civil Defence Reference: ________________    "
                  "ADCDA Compliance Certification: This inspection was conducted in accordance with",
                  ln=True)
        self.cell(0, 4,
                  "UAE Fire and Life Safety Code of Practice and applicable NFPA standards. "
                  "Report generated by TTS Guard AMC Management System.",
                  ln=True)
        self.ln(2)
        self.set_font("Helvetica", "", 7)
        self.cell(0, 4, f"Page {self.page_no()}/{{nb}}", align="C")

    def add_section_header(self, title):
        """Add a colored section header."""
        self.set_font("Helvetica", "B", 11)
        self.set_fill_color(250, 250, 250)
        self.set_text_color(211, 47, 47)
        self.cell(0, 8, f"  {title}", ln=True, fill=True)
        self.set_text_color(33, 33, 33)
        self.ln(2)

    def add_key_value(self, key, value, bold_value=False):
        """Add a key: value line."""
        self.set_font("Helvetica", "", 9)
        self.cell(50, 6, key + ":", align="R")
        self.set_font("Helvetica", "B" if bold_value else "", 9)
        self.cell(0, 6, f"  {value}", ln=True)

    def add_table_header(self, headers, widths):
        """Add a table header row."""
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(211, 47, 47)
        self.set_text_color(255, 255, 255)
        for header, width in zip(headers, widths):
            self.cell(width, 7, f" {header}", border=1, fill=True)
        self.ln()
        self.set_text_color(33, 33, 33)

    def add_table_row(self, values, widths, fill=False):
        """Add a table data row."""
        self.set_font("Helvetica", "", 8)
        if fill:
            self.set_fill_color(248, 248, 248)
        for value, width in zip(values, widths):
            self.cell(width, 6, f" {str(value)}", border=1, fill=fill)
        self.ln()


def generate_inspection_pdf(
    building_name,
    client_name,
    inspection_date,
    technician,
    items_checked,
    items_passed,
    items_failed,
    equipment_details,
    notes="",
):
    """
    Generate a professional inspection report PDF.

    Args:
        building_name: Name of the building inspected
        client_name: Client company name
        inspection_date: Date of inspection (str or date)
        technician: Technician name
        items_checked: Total items checked
        items_passed: Items that passed
        items_failed: Items that failed
        equipment_details: List of dicts with keys: type, status ('Passed'/'Failed')
        notes: Inspection notes

    Returns:
        bytes: PDF file content
    """
    pdf = InspectionReport(building_name, client_name)
    pdf.alias_nb_pages()
    pdf.add_page()

    # ----- INSPECTION DETAILS -----
    pdf.add_section_header("Inspection Details")
    pdf.add_key_value("Client", client_name, bold_value=True)
    pdf.add_key_value("Building", building_name, bold_value=True)
    pdf.add_key_value("Inspection Date", str(inspection_date))
    pdf.add_key_value("Inspector", technician)
    pdf.add_key_value("Report Date", date.today().isoformat())
    pdf.ln(4)

    # ----- SUMMARY -----
    pdf.add_section_header("Inspection Summary")

    col_w = 60
    pdf.set_font("Helvetica", "B", 20)

    # Systems checked
    pdf.set_x(15)
    pdf.set_text_color(33, 33, 33)
    pdf.cell(col_w, 12, str(items_checked), align="C")
    # Passed
    pdf.set_text_color(0, 200, 83)  # green
    pdf.cell(col_w, 12, str(items_passed), align="C")
    # Failed
    pdf.set_text_color(211, 47, 47)  # red
    pdf.cell(col_w, 12, str(items_failed), align="C")
    pdf.ln()

    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(100, 100, 100)
    pdf.set_x(15)
    pdf.cell(col_w, 5, "Systems Checked", align="C")
    pdf.cell(col_w, 5, "Passed", align="C")
    pdf.cell(col_w, 5, "Needs Attention", align="C")
    pdf.ln(8)

    # Pass rate bar
    pass_rate = (items_passed / items_checked * 100) if items_checked > 0 else 0
    bar_width = 180
    pdf.set_x(15)
    # Background
    pdf.set_fill_color(230, 230, 230)
    pdf.rect(15, pdf.get_y(), bar_width, 6, "F")
    # Fill
    if pass_rate >= 90:
        pdf.set_fill_color(0, 200, 83)
    elif pass_rate >= 70:
        pdf.set_fill_color(255, 165, 0)
    else:
        pdf.set_fill_color(211, 47, 47)
    pdf.rect(15, pdf.get_y(), bar_width * pass_rate / 100, 6, "F")
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_text_color(33, 33, 33)
    pdf.cell(bar_width, 6, f"  Pass Rate: {pass_rate:.1f}%", align="C")
    pdf.ln(10)

    # ----- EQUIPMENT CHECKLIST -----
    pdf.add_section_header("Equipment Checklist")

    headers = ["#", "Equipment Type", "Status", "Remarks"]
    widths = [10, 80, 30, 70]
    pdf.add_table_header(headers, widths)

    for idx, item in enumerate(equipment_details):
        status_text = item.get("status", "Passed")
        remarks = "OK" if status_text == "Passed" else "Requires attention"
        pdf.add_table_row(
            [str(idx + 1), item["type"], status_text, remarks],
            widths,
            fill=(idx % 2 == 0),
        )

    pdf.ln(6)

    # ----- NOTES -----
    if notes:
        pdf.add_section_header("Inspector Notes")
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, notes)
        pdf.ln(4)

    # ----- SIGNATURES -----
    pdf.add_section_header("Signatures")

    pdf.set_font("Helvetica", "", 9)
    sig_width = 85

    pdf.set_x(15)
    pdf.cell(sig_width, 6, "Inspector:", ln=False)
    pdf.cell(sig_width, 6, "Client Representative:", ln=True)

    pdf.ln(10)

    pdf.set_x(15)
    pdf.line(15, pdf.get_y(), 15 + sig_width - 10, pdf.get_y())
    pdf.line(15 + sig_width + 5, pdf.get_y(), 15 + 2 * sig_width - 5, pdf.get_y())
    pdf.ln(3)

    pdf.set_x(15)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(sig_width, 5, f"Name: {technician}")
    pdf.cell(sig_width, 5, "Name: ________________________", ln=True)

    pdf.set_x(15)
    pdf.cell(sig_width, 5, f"Date: {inspection_date}")
    pdf.cell(sig_width, 5, f"Date: {inspection_date}", ln=True)

    # Return as bytes
    return pdf.output()
